apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-app
    version: "blue"
  name: node-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      version: "blue"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app
        version: "blue"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/iit-cc/iit-cc/node-app:3.2.0
        name: node-app
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ENV
        resources: {}
status: {}


