apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-app
  name: node-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-app
    version: "blue"
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "node-app-hpa-wvpn"
  namespace: "default"
  labels:
    app: "node-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "node-app-blue"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80