name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your branch

env:
  TAG: 2.0.0
  IMAGE: node-app


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'            

      - name: Configure Docker Client of Gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
        
      - name: Build the Docker image
        run: |
          docker build \
            --build-arg DB_HOST=$DB_HOST \
            --build-arg DB_USER=$DB_USER \
            --build-arg DB_PASSWORD=$DB_PASSWORD \
            --build-arg DB_NAME=$DB_NAME \
            -t $IMAGE .

      - name: Tag the Docker image
        run: docker tag $IMAGE us-central1-docker.pkg.dev/iit-cc/iit-cc/$IMAGE:$TAG

      - name: Push Docker image to Google Cloud Registry
        run: docker push us-central1-docker.pkg.dev/iit-cc/iit-cc/$IMAGE:$TAG