# This is a basic workflow that is manually triggered

name: Deploy to Production

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy Version'
        # Default value if no value is explicitly provided
        default: 'v1.0.0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

env:
  IMAGE: node-app
  GKE_CLUSTER: prod-cluster-iit    
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: node-app
  CONTAINER: node-app-sha256-1
  REPO: us-central1-docker.pkg.dev/iit-cc/iit-cc 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy to PROD
        run: |-
          # replacing the image name in the k8s template
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER=$REPO/node-app:'${{ inputs.tag }}'
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
          
    
