# This is a basic workflow that is manually triggered

name: Removing Redundent Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      color:
        description: 'Removal Deployment type blue/green'
        # Default value if no value is explicitly provided
        default: 'green'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: choice
        options:
          - blue
          - green
  
env:
  GKE_CLUSTER: prod-cluster-iit    
  GKE_ZONE: us-central1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Check out code
        uses: actions/checkout@v4.1.1
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster
      - name: Remove Blue/Green from Kubernetes
        run: |
          # Determine which color to deploy based on input color
          if [ "${{ github.event.inputs.color }}" == blue ]; then
            kubectl delete -f deployments/node-version-blue.yaml
          elif [ "${{ github.event.inputs.color }}" == green ]; then
            kubectl delete -f deployments/node-version-green.yaml
          else
            echo "Invalid color provided. Please provide 'blue' or 'green'."
            exit 1
          fi
          
    
